baseURL = "https://openstreetmap.de/"
languageCode = "de-de"
title = "OpenStreetMap Deutschland"
disableKinds = ["taxonomy", "taxonomyTerm"]

# Info über letzte Änderung einer Seite kommt aus dem git
enableGitInfo = true

[security]
enableInlineShortcodes = true

############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.111.3"

############################# Image Processing ##############################
[imaging]
quality = 95

############################# Outputs ##############################
[outputs]
home = ["html", "json"] # JSON der Homepage wird für die Suche benötigt
section = ['html'] # Andere Seiten nur als HTML, kein RSS

[markup.goldmark.renderer]
unsafe= true

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]

# JS Plugins
[[params.plugins.js]]

#################### default parameters ################################
[params]
favicon = "img/favicon.ico"
# Meta data
description = "OpenStreetMap Deutschland"
author = "FOSSGIS e.V."
# search
search = false
copyright = "FOSSGIS e.V"
githubLink = "https://github.com/fossgis/openstreetmap.de/blob/main"

