baseURL = "https://openstreetmap.de/"
languageCode = "de-de"
title = "OpenStreetMap Deutschland"
disableKinds = ["taxonomy", "taxonomyTerm"]

############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.111.3"

############################# Image Processing ##############################
[imaging]
quality = 95

############################# Outputs ##############################
[outputs]
home = ["HTML", "JSON"]

[markup.goldmark.renderer]
unsafe= true

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]

# JS Plugins
[[params.plugins.js]]

#################### default parameters ################################
[params]
favicon = "img/favicon.ico"
# Meta data
description = "OpenStreetMap Deutschland"
author = "FOSSGIS e.V."
# search
search = false
copyright = "FOSSGIS e.V"
githubLink = "https://github.com/fossgis/openstreetmap.de/blob/main"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# Main Menu ########################
[[menu.main]]
name = "Das Projekt"
url = "projekt/"
weight = 1

[[menu.main]]
name = "OSM nutzen"
url = "nutzen/"
weight = 2

[[menu.main]]
name = "Beitragen"
url = "beitragen/"
weight = 3

[[menu.main]]
name = "Community"
url = "community/"
weight = 4

[[menu.main]]
name = "Themenportal"
url = "themen/"
weight = 5

[[menu.main]]
name = "Kontakt"
url = "kontakt/"
weight = 6

[[menu.main]]
name = ""
url = ""
pre = ''
weight = 7

[[menu.main]]
name = "Veranstaltungen"
url = "veranstaltungen/"
weight = 8
[menu.main.params]
    short = true

[[menu.main]]
name = "Spenden"
url = "spenden/"
weight = 9
[menu.main.params]
    short = true

[[menu.main]]
name = "Shop"
url = "shop/"
weight = 10
[menu.main.params]
    short = true

